" https://dougblack.io/words/a-good-vimrc.html
syntax enable  " enable syntax processing

set background=dark  " Setting dark mode
let g:gruvbox_contrast_dark='hard'
let g:gruvbox_italic=1
let g:gruvbox_termcolors=16
colorscheme gruvbox

set tabstop=2  " number of visual spaces per TAB
set softtabstop=2  " number of spaces in tab when editing
set expandtab  " tabs are spaces
set shiftwidth=2  " indenting with two spaces

set relativenumber  " Show relative line numbers
set showcmd  " show command in bottom bar
set cursorline  " highlight current line
filetype indent on  " load filetype-specific indent file
set wildmenu  " visual autocomplete for command menu
set lazyredraw  " redraw only when we need to.
set showmatch  " highlight matching [{()}]

set incsearch  " search as characters are entered
set hlsearch  " highlight matches
set laststatus=2  " see current filename

" http://vim.wikia.com/wiki/Word_wrap_without_line_breaks
set wrap " word wrap without line breaks
set linebreak
set nolist " list disables linebreak

" move vertically by visual line
nnoremap j gj
nnoremap k gk

" rulers at columns
" https://stackoverflow.com/questions/50317382/how-set-set-multiple-color-columns-cc-set-colorcolumn-in-vim
" https://codeyarns.com/2011/07/29/vim-set-color-of-colorcolumn/
set colorcolumn=80,100,120

" default Prettier configuration, <leader> p to prettier code
" https://github.com/prettier/vim-prettier
let g:prettier#exec_cmd_async = 1 " formatting without saving

" max line length that prettier will wrap on
" Prettier default: 80
let g:prettier#config#print_width = 80

" number of spaces per indentation level
" Prettier default: 2
let g:prettier#config#tab_width = 2

" use tabs over spaces
" Prettier default: false
let g:prettier#config#use_tabs = 'false'

" print semicolons
" Prettier default: true
let g:prettier#config#semi = 'true'

" single quotes over double quotes
" Prettier default: false
let g:prettier#config#single_quote = 'true'

" print spaces between brackets
" Prettier default: true
let g:prettier#config#bracket_spacing = 'true'

" put > on the last line instead of new line
" Prettier default: false
let g:prettier#config#jsx_bracket_same_line = 'false'

" avoid|always
" Prettier default: avoid
let g:prettier#config#arrow_parens = 'avoid'

" none|es5|all
" Prettier default: none
let g:prettier#config#trailing_comma = 'none'

" flow|babylon|typescript|css|less|scss|json|graphql|markdown
" Prettier default: babylon
let g:prettier#config#parser = 'babylon'

" cli-override|file-override|prefer-file
let g:prettier#config#config_precedence = 'prefer-file'

" always|never|preserve
let g:prettier#config#prose_wrap = 'preserve'
