syntax enable  " enable syntax processing

colorscheme cobalt2
set tabstop=2  " number of visual spaces per TAB
set softtabstop=2  " number of spaces in tab when editing
set expandtab  " tabs are spaces

set relativenumber  " Show relative line numbers
set showcmd  " show command in bottom bar
set cursorline  " highlight current line
filetype indent on  " load filetype-specific indent file
set wildmenu  " visual autocomplete for command menu
set lazyredraw  " redraw only when we need to.
set showmatch  " highlight matching [{()}]

set incsearch  " search as characters are entered
set hlsearch  " highlight matches
set guifont=Fira\ Code  " set font
set laststatus=2  " see current filename
